import * as fs from 'node:fs';
import * as path from 'node:path';
import designTokens from '../designTokens/designTokens.json';

const VERA_DARK_MODE_CLASS = 'vera-dark-mode';
const pluginFile = path.resolve('libs/ui/src/theme/helpers/tailwind/veraUI.cjs');

/**
 * Generates a comprehensive Tailwind plugin with all Vera design tokens.
 * This script reads from designTokens.json and generates veraUI.cjs
 * The plugin extends Tailwind's theme with semantic tokens that are:
 * - Theme-aware (colors respond to .dark class via CSS variables)
 * - Responsive (font sizes respond to screen size)
 * - Overridable by the user
 */
function generateVeraUIPlugin() {
  const { colorVariables, colorTokens } = generateColorTokens(
    designTokens.colors.light,
    designTokens.colors.dark
  );
  const borderRadius = generateBorderRadiusTokens(designTokens.borderRadius);
  const fontFamily = generateFontFamilyTokens(designTokens.fontFamily);
  const screens = {
    'vera-mobile': { max: '767px' },
    'vera-desktop': { min: '768px' },
  };

  let plugin = `/**
 * Auto-generated Tailwind plugin for Vera design system
 * DO NOT EDIT MANUALLY - Generated by generateTailwindPlugin.ts
 */
const plugin = require('tailwindcss/plugin');

const veraUI = plugin(({ addUtilities, addBase, addVariant }) => {
  const fontSizeUtilities = {};
  const fontWeightUtilities = {};

  // Add custom variants
  addVariant('child', '& > *');

  // Add CSS variables for theme-aware colors
  addBase({
    ':root': ${JSON.stringify(colorVariables.root, null, 6).replace(/\n/g, '\n    ')},
    'html.vera-dark-mode': ${JSON.stringify(colorVariables.dark, null, 6).replace(/\n/g, '\n    ')},
  });

`;

  const { desktop: fontSizeDesktop, mobile: fontSizeMobile } = designTokens.fontSize;

  // Generate font size utilities
  for (const key of Object.keys(fontSizeDesktop)) {
    const desktop = fontSizeDesktop[key as keyof typeof fontSizeDesktop];
    const mobile = fontSizeMobile[key as keyof typeof fontSizeMobile];

    plugin += `  // ${key}\n`;
    plugin += `  fontSizeUtilities['.text-vera-${key}'] = {\n`;
    plugin += `    fontSize: '${mobile.fontSize}',\n`;
    plugin += `    lineHeight: '${mobile.lineHeight}',\n`;
    plugin += `    fontWeight: ${mobile.fontWeight},\n`;
    plugin += `    '@media (min-width: 768px)': {\n`;
    plugin += `      fontSize: '${desktop.fontSize}',\n`;
    plugin += `      lineHeight: '${desktop.lineHeight}',\n`;
    plugin += `      fontWeight: ${desktop.fontWeight},\n`;
    plugin += `    },\n`;
    plugin += `  };\n\n`;

    // Generate responsive font weight utilities
    plugin += `  fontWeightUtilities['.font-vera-${key}'] = {\n`;
    plugin += `    fontWeight: ${mobile.fontWeight},\n`;
    plugin += `    '@media (min-width: 768px)': {\n`;
    plugin += `      fontWeight: ${desktop.fontWeight},\n`;
    plugin += `    },\n`;
    plugin += `  };\n\n`;
  }

  plugin += `  addUtilities(fontSizeUtilities);
  addUtilities(fontWeightUtilities);
}, {
  theme: {
    extend: {
      borderRadius: ${JSON.stringify(borderRadius, null, 6).replace(/\n/g, '\n      ')},
      colors: ${JSON.stringify(colorTokens, null, 6).replace(/\n/g, '\n      ')},
      fontFamily: ${JSON.stringify(fontFamily, null, 6).replace(/\n/g, '\n      ')},
      screens: ${JSON.stringify(screens, null, 6).replace(/\n/g, '\n      ')},
    },
  },
});

veraUI.safelist = ['${VERA_DARK_MODE_CLASS}'];

module.exports = veraUI;
`;

  fs.mkdirSync(path.dirname(pluginFile), { recursive: true });
  fs.writeFileSync(pluginFile, plugin, 'utf-8');
  console.log(`\x1b[32m✔ Tailwind plugin written to ${pluginFile}\x1b[0m`);
}

/**
 * Generates theme-aware color tokens with CSS variables.
 * Creates CSS custom properties that respond to theme changes via body.dark class.
 *
 * Returns:
 * - colorVariables: CSS variables for :root and body.dark
 * - colorTokens: Tailwind color tokens that reference the CSS variables
 *
 * Generated variants:
 * - vera-{key}: theme-aware (uses --vera-{key} variable)
 * - vera-{key}-light: static light color (uses --vera-{key}-light variable)
 * - vera-{key}-dark: static dark color (uses --vera-{key}-dark variable)
 *
 * Tokens are sorted alphabetically by base name for consistent output.
 *
 * Usage:
 *   className="bg-vera-primary" (theme-aware)
 *   className="bg-vera-primary-light" (always light)
 *   className="bg-vera-primary-dark" (always dark)
 */
function generateColorTokens(
  lightColors: Record<string, string>,
  darkColors: Record<string, string>
): {
  colorVariables: { root: Record<string, string>; dark: Record<string, string> };
  colorTokens: Record<string, string>;
} {
  const rootVariables: Record<string, string> = {};
  const darkVariables: Record<string, string> = {};
  const colorTokens: Record<string, string> = {};

  // Sort keys alphabetically for consistent output
  const sortedKeys = Object.keys(lightColors).sort((a, b) => a.localeCompare(b));

  // Generate CSS variables and color tokens
  for (const key of sortedKeys) {
    const light = lightColors[key];
    const dark = darkColors[key];

    // CSS variables for theme-aware color
    rootVariables[`--vera-${key}`] = light;
    darkVariables[`--vera-${key}`] = dark;

    // CSS variables for static variants (don't change with theme)
    rootVariables[`--vera-${key}-light`] = light;
    rootVariables[`--vera-${key}-dark`] = dark;

    // Tailwind color tokens that reference CSS variables with fallback values
    colorTokens[`vera-${key}`] = `var(--vera-${key}, ${light})`;
    colorTokens[`vera-${key}-light`] = `var(--vera-${key}-light, ${light})`;
    colorTokens[`vera-${key}-dark`] = `var(--vera-${key}-dark, ${dark})`;
  }

  return {
    colorVariables: {
      root: rootVariables,
      dark: darkVariables,
    },
    colorTokens,
  };
}

/**
 * Generates border radius tokens with vera- prefix.
 * Tokens are sorted alphabetically for consistent output.
 */
function generateBorderRadiusTokens(shape: Record<string, string>): Record<string, string> {
  const borderRadius: Record<string, string> = {};

  // Sort keys alphabetically for consistent output
  const sortedKeys = Object.keys(shape).sort((a, b) => a.localeCompare(b));

  for (const key of sortedKeys) {
    borderRadius[`vera-${key}`] = shape[key];
  }

  return borderRadius;
}

/**
 * Generates font family tokens with vera- prefix.
 * Tokens are sorted alphabetically for consistent output.
 */
function generateFontFamilyTokens(typeface: Record<string, string>): Record<string, string[]> {
  const fontFamily: Record<string, string[]> = {};

  // Sort keys alphabetically for consistent output
  const sortedKeys = Object.keys(typeface).sort((a, b) => a.localeCompare(b));

  for (const key of sortedKeys) {
    fontFamily[`vera-${key}`] = typeface[key].split(', ');
  }

  return fontFamily;
}

// Run the generation
generateVeraUIPlugin();
