/**
 * Auto-generated Tailwind plugin for Vera design system
 * DO NOT EDIT MANUALLY - Generated by generateTailwindPlugin.ts
 */
const plugin = require('tailwindcss/plugin');

const veraUI = plugin(
  ({ addUtilities, addBase, addVariant }) => {
    const fontSizeUtilities = {};
    const fontWeightUtilities = {};

    // Add custom variants
    addVariant('child', '& > *');

    // Add CSS variables for theme-aware colors
    addBase({
      ':root': {
        '--vera-accent': '#FFFFFF',
        '--vera-accent-light': '#FFFFFF',
        '--vera-accent-dark': '#FFFFFF',
        '--vera-alert-background': '#FFEEF2',
        '--vera-alert-background-light': '#FFEEF2',
        '--vera-alert-background-dark': '#3E0004',
        '--vera-alert-background-hover': '#FEDFDF',
        '--vera-alert-background-hover-light': '#FEDFDF',
        '--vera-alert-background-hover-dark': '#6E0000',
        '--vera-alert-text': '#CD0000',
        '--vera-alert-text-light': '#CD0000',
        '--vera-alert-text-dark': '#FEDFDF',
        '--vera-background': '#F5F0FD',
        '--vera-background-light': '#F5F0FD',
        '--vera-background-dark': '#26044D',
        '--vera-border': '#E6E6E6',
        '--vera-border-light': '#E6E6E6',
        '--vera-border-dark': '#333333',
        '--vera-dark-background': '#202124',
        '--vera-dark-background-light': '#202124',
        '--vera-dark-background-dark': '#202124',
        '--vera-dark-grey': '#333333',
        '--vera-dark-grey-light': '#333333',
        '--vera-dark-grey-dark': '#333333',
        '--vera-dark-grey-hover': '#292828',
        '--vera-dark-grey-hover-light': '#292828',
        '--vera-dark-grey-hover-dark': '#292828',
        '--vera-dark-grey-opacity': '#333333CD',
        '--vera-dark-grey-opacity-light': '#333333CD',
        '--vera-dark-grey-opacity-dark': '#333333CD',
        '--vera-disabled': '#E6E6E6',
        '--vera-disabled-light': '#E6E6E6',
        '--vera-disabled-dark': '#333333',
        '--vera-error': '#E61D1D',
        '--vera-error-light': '#E61D1D',
        '--vera-error-dark': '#F75959',
        '--vera-error-hover': '#CD0000',
        '--vera-error-hover-light': '#CD0000',
        '--vera-error-hover-dark': '#FE9696',
        '--vera-information': '#0276D5',
        '--vera-information-light': '#0276D5',
        '--vera-information-dark': '#2997F0',
        '--vera-information-background': '#E8F4FB',
        '--vera-information-background-light': '#E8F4FB',
        '--vera-information-background-dark': '#E8F4FB',
        '--vera-information-hover': '#2997F0',
        '--vera-information-hover-light': '#2997F0',
        '--vera-information-hover-dark': '#0276D5',
        '--vera-on-accent': '#000000',
        '--vera-on-accent-light': '#000000',
        '--vera-on-accent-dark': '#000000',
        '--vera-on-background': '#757575',
        '--vera-on-background-light': '#757575',
        '--vera-on-background-dark': '#B3B3B3',
        '--vera-on-dark-grey': '#FFFFFF',
        '--vera-on-dark-grey-light': '#FFFFFF',
        '--vera-on-dark-grey-dark': '#FFFFFF',
        '--vera-on-error': '#FFFFFF',
        '--vera-on-error-light': '#FFFFFF',
        '--vera-on-error-dark': '#000000',
        '--vera-on-information': '#FFFFFF',
        '--vera-on-information-light': '#FFFFFF',
        '--vera-on-information-dark': '#FFFFFF',
        '--vera-on-primary': '#FFFFFF',
        '--vera-on-primary-light': '#FFFFFF',
        '--vera-on-primary-dark': '#000000',
        '--vera-on-secondary': '#FFFFFF',
        '--vera-on-secondary-light': '#FFFFFF',
        '--vera-on-secondary-dark': '#000000',
        '--vera-on-success': '#FFFFFF',
        '--vera-on-success-light': '#FFFFFF',
        '--vera-on-success-dark': '#000000',
        '--vera-on-surface': '#929292',
        '--vera-on-surface-light': '#929292',
        '--vera-on-surface-dark': '#FFFFFF',
        '--vera-on-tertiary': '#FFFFFF',
        '--vera-on-tertiary-light': '#FFFFFF',
        '--vera-on-tertiary-dark': '#000000',
        '--vera-on-warning': '#FFFFFF',
        '--vera-on-warning-light': '#FFFFFF',
        '--vera-on-warning-dark': '#000000',
        '--vera-primary': '#9941FF',
        '--vera-primary-light': '#9941FF',
        '--vera-primary-dark': '#B27BF2',
        '--vera-primary-hover': '#871EFF',
        '--vera-primary-hover-light': '#871EFF',
        '--vera-primary-hover-dark': '#CBA1FA',
        '--vera-secondary': '#000000',
        '--vera-secondary-light': '#000000',
        '--vera-secondary-dark': '#FFFFFF',
        '--vera-secondary-hover': '#666666',
        '--vera-secondary-hover-light': '#666666',
        '--vera-secondary-hover-dark': '#929292',
        '--vera-skeleton-like': '#B3B3B3',
        '--vera-skeleton-like-light': '#B3B3B3',
        '--vera-skeleton-like-dark': '#333333',
        '--vera-success': '#1C8731',
        '--vera-success-light': '#1C8731',
        '--vera-success-dark': '#30A849',
        '--vera-success-hover': '#1F7629',
        '--vera-success-hover-light': '#1F7629',
        '--vera-success-hover-dark': '#53CA6A',
        '--vera-surface': '#FFFFFF',
        '--vera-surface-light': '#FFFFFF',
        '--vera-surface-dark': '#000000',
        '--vera-tertiary': '#757575',
        '--vera-tertiary-light': '#757575',
        '--vera-tertiary-dark': '#B3B3B3',
        '--vera-tertiary-hover': '#929292',
        '--vera-tertiary-hover-light': '#929292',
        '--vera-tertiary-hover-dark': '#B3B3B3',
        '--vera-text-disabled': '#B3B3B3',
        '--vera-text-disabled-light': '#B3B3B3',
        '--vera-text-disabled-dark': '#666666',
        '--vera-text-primary': '#9941FF',
        '--vera-text-primary-light': '#9941FF',
        '--vera-text-primary-dark': '#B27BF2',
        '--vera-text-secondary': '#000000',
        '--vera-text-secondary-light': '#000000',
        '--vera-text-secondary-dark': '#FFFFFF',
        '--vera-text-tertiary': '#757575',
        '--vera-text-tertiary-light': '#757575',
        '--vera-text-tertiary-dark': '#B3B3B3',
        '--vera-warning': '#BE5702',
        '--vera-warning-light': '#BE5702',
        '--vera-warning-dark': '#FA9F00',
        '--vera-warning-hover': '#A64C03',
        '--vera-warning-hover-light': '#A64C03',
        '--vera-warning-hover-dark': '#FACC4B',
      },
      'html.vera-dark-mode': {
        '--vera-accent': '#FFFFFF',
        '--vera-alert-background': '#3E0004',
        '--vera-alert-background-hover': '#6E0000',
        '--vera-alert-text': '#FEDFDF',
        '--vera-background': '#26044D',
        '--vera-border': '#333333',
        '--vera-dark-background': '#202124',
        '--vera-dark-grey': '#333333',
        '--vera-dark-grey-hover': '#292828',
        '--vera-dark-grey-opacity': '#333333CD',
        '--vera-disabled': '#333333',
        '--vera-error': '#F75959',
        '--vera-error-hover': '#FE9696',
        '--vera-information': '#2997F0',
        '--vera-information-background': '#E8F4FB',
        '--vera-information-hover': '#0276D5',
        '--vera-on-accent': '#000000',
        '--vera-on-background': '#B3B3B3',
        '--vera-on-dark-grey': '#FFFFFF',
        '--vera-on-error': '#000000',
        '--vera-on-information': '#FFFFFF',
        '--vera-on-primary': '#000000',
        '--vera-on-secondary': '#000000',
        '--vera-on-success': '#000000',
        '--vera-on-surface': '#FFFFFF',
        '--vera-on-tertiary': '#000000',
        '--vera-on-warning': '#000000',
        '--vera-primary': '#B27BF2',
        '--vera-primary-hover': '#CBA1FA',
        '--vera-secondary': '#FFFFFF',
        '--vera-secondary-hover': '#929292',
        '--vera-skeleton-like': '#333333',
        '--vera-success': '#30A849',
        '--vera-success-hover': '#53CA6A',
        '--vera-surface': '#000000',
        '--vera-tertiary': '#B3B3B3',
        '--vera-tertiary-hover': '#B3B3B3',
        '--vera-text-disabled': '#666666',
        '--vera-text-primary': '#B27BF2',
        '--vera-text-secondary': '#FFFFFF',
        '--vera-text-tertiary': '#B3B3B3',
        '--vera-warning': '#FA9F00',
        '--vera-warning-hover': '#FACC4B',
      },
    });

    // headline
    fontSizeUtilities['.text-vera-headline'] = {
      fontSize: '2rem',
      lineHeight: '2.5rem',
      fontWeight: 500,
      '@media (min-width: 768px)': {
        fontSize: '4.125rem',
        lineHeight: '5.5rem',
        fontWeight: 500,
      },
    };

    fontWeightUtilities['.font-vera-headline'] = {
      fontWeight: 500,
      '@media (min-width: 768px)': {
        fontWeight: 500,
      },
    };

    // subtitle
    fontSizeUtilities['.text-vera-subtitle'] = {
      fontSize: '1.875rem',
      lineHeight: '2.375rem',
      fontWeight: 500,
      '@media (min-width: 768px)': {
        fontSize: '3.25rem',
        lineHeight: '4.25rem',
        fontWeight: 500,
      },
    };

    fontWeightUtilities['.font-vera-subtitle'] = {
      fontWeight: 500,
      '@media (min-width: 768px)': {
        fontWeight: 500,
      },
    };

    // heading-1
    fontSizeUtilities['.text-vera-heading-1'] = {
      fontSize: '1.75rem',
      lineHeight: '2.25rem',
      fontWeight: 500,
      '@media (min-width: 768px)': {
        fontSize: '2.5rem',
        lineHeight: '3.25rem',
        fontWeight: 500,
      },
    };

    fontWeightUtilities['.font-vera-heading-1'] = {
      fontWeight: 500,
      '@media (min-width: 768px)': {
        fontWeight: 500,
      },
    };

    // heading-2
    fontSizeUtilities['.text-vera-heading-2'] = {
      fontSize: '1.5rem',
      lineHeight: '2rem',
      fontWeight: 500,
      '@media (min-width: 768px)': {
        fontSize: '2rem',
        lineHeight: '2.75rem',
        fontWeight: 500,
      },
    };

    fontWeightUtilities['.font-vera-heading-2'] = {
      fontWeight: 500,
      '@media (min-width: 768px)': {
        fontWeight: 500,
      },
    };

    // heading-3
    fontSizeUtilities['.text-vera-heading-3'] = {
      fontSize: '1.25rem',
      lineHeight: '1.75rem',
      fontWeight: 500,
      '@media (min-width: 768px)': {
        fontSize: '1.625rem',
        lineHeight: '2.25rem',
        fontWeight: 500,
      },
    };

    fontWeightUtilities['.font-vera-heading-3'] = {
      fontWeight: 500,
      '@media (min-width: 768px)': {
        fontWeight: 500,
      },
    };

    // heading-4
    fontSizeUtilities['.text-vera-heading-4'] = {
      fontSize: '1.125rem',
      lineHeight: '1.5rem',
      fontWeight: 500,
      '@media (min-width: 768px)': {
        fontSize: '1.25rem',
        lineHeight: '1.75rem',
        fontWeight: 500,
      },
    };

    fontWeightUtilities['.font-vera-heading-4'] = {
      fontWeight: 500,
      '@media (min-width: 768px)': {
        fontWeight: 500,
      },
    };

    // body-extended
    fontSizeUtilities['.text-vera-body-extended'] = {
      fontSize: '1rem',
      lineHeight: '1.5rem',
      fontWeight: 400,
      '@media (min-width: 768px)': {
        fontSize: '1rem',
        lineHeight: '1.5rem',
        fontWeight: 400,
      },
    };

    fontWeightUtilities['.font-vera-body-extended'] = {
      fontWeight: 400,
      '@media (min-width: 768px)': {
        fontWeight: 400,
      },
    };

    // body-extended-semibold
    fontSizeUtilities['.text-vera-body-extended-semibold'] = {
      fontSize: '1rem',
      lineHeight: '1.5rem',
      fontWeight: 600,
      '@media (min-width: 768px)': {
        fontSize: '1rem',
        lineHeight: '1.5rem',
        fontWeight: 600,
      },
    };

    fontWeightUtilities['.font-vera-body-extended-semibold'] = {
      fontWeight: 600,
      '@media (min-width: 768px)': {
        fontWeight: 600,
      },
    };

    // body-base
    fontSizeUtilities['.text-vera-body-base'] = {
      fontSize: '0.875rem',
      lineHeight: '1.25rem',
      fontWeight: 400,
      '@media (min-width: 768px)': {
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        fontWeight: 400,
      },
    };

    fontWeightUtilities['.font-vera-body-base'] = {
      fontWeight: 400,
      '@media (min-width: 768px)': {
        fontWeight: 400,
      },
    };

    // body-base-semibold
    fontSizeUtilities['.text-vera-body-base-semibold'] = {
      fontSize: '0.875rem',
      lineHeight: '1.25rem',
      fontWeight: 600,
      '@media (min-width: 768px)': {
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        fontWeight: 600,
      },
    };

    fontWeightUtilities['.font-vera-body-base-semibold'] = {
      fontWeight: 600,
      '@media (min-width: 768px)': {
        fontWeight: 600,
      },
    };

    // caption
    fontSizeUtilities['.text-vera-caption'] = {
      fontSize: '0.75rem',
      lineHeight: '1rem',
      fontWeight: 400,
      '@media (min-width: 768px)': {
        fontSize: '0.75rem',
        lineHeight: '1rem',
        fontWeight: 400,
      },
    };

    fontWeightUtilities['.font-vera-caption'] = {
      fontWeight: 400,
      '@media (min-width: 768px)': {
        fontWeight: 400,
      },
    };

    // caption-semibold
    fontSizeUtilities['.text-vera-caption-semibold'] = {
      fontSize: '0.75rem',
      lineHeight: '1rem',
      fontWeight: 600,
      '@media (min-width: 768px)': {
        fontSize: '0.75rem',
        lineHeight: '1rem',
        fontWeight: 600,
      },
    };

    fontWeightUtilities['.font-vera-caption-semibold'] = {
      fontWeight: 600,
      '@media (min-width: 768px)': {
        fontWeight: 600,
      },
    };

    addUtilities(fontSizeUtilities);
    addUtilities(fontWeightUtilities);
  },
  {
    theme: {
      extend: {
        borderRadius: {
          'vera-extra-large': '24px',
          'vera-extra-small': '2px',
          'vera-large': '12px',
          'vera-medium': '8px',
          'vera-none': '0px',
          'vera-small': '4px',
        },
        colors: {
          'vera-accent': 'var(--vera-accent, #FFFFFF)',
          'vera-accent-light': 'var(--vera-accent-light, #FFFFFF)',
          'vera-accent-dark': 'var(--vera-accent-dark, #FFFFFF)',
          'vera-alert-background': 'var(--vera-alert-background, #FFEEF2)',
          'vera-alert-background-light': 'var(--vera-alert-background-light, #FFEEF2)',
          'vera-alert-background-dark': 'var(--vera-alert-background-dark, #3E0004)',
          'vera-alert-background-hover': 'var(--vera-alert-background-hover, #FEDFDF)',
          'vera-alert-background-hover-light': 'var(--vera-alert-background-hover-light, #FEDFDF)',
          'vera-alert-background-hover-dark': 'var(--vera-alert-background-hover-dark, #6E0000)',
          'vera-alert-text': 'var(--vera-alert-text, #CD0000)',
          'vera-alert-text-light': 'var(--vera-alert-text-light, #CD0000)',
          'vera-alert-text-dark': 'var(--vera-alert-text-dark, #FEDFDF)',
          'vera-background': 'var(--vera-background, #F5F0FD)',
          'vera-background-light': 'var(--vera-background-light, #F5F0FD)',
          'vera-background-dark': 'var(--vera-background-dark, #26044D)',
          'vera-border': 'var(--vera-border, #E6E6E6)',
          'vera-border-light': 'var(--vera-border-light, #E6E6E6)',
          'vera-border-dark': 'var(--vera-border-dark, #333333)',
          'vera-dark-background': 'var(--vera-dark-background, #202124)',
          'vera-dark-background-light': 'var(--vera-dark-background-light, #202124)',
          'vera-dark-background-dark': 'var(--vera-dark-background-dark, #202124)',
          'vera-dark-grey': 'var(--vera-dark-grey, #333333)',
          'vera-dark-grey-light': 'var(--vera-dark-grey-light, #333333)',
          'vera-dark-grey-dark': 'var(--vera-dark-grey-dark, #333333)',
          'vera-dark-grey-hover': 'var(--vera-dark-grey-hover, #292828)',
          'vera-dark-grey-hover-light': 'var(--vera-dark-grey-hover-light, #292828)',
          'vera-dark-grey-hover-dark': 'var(--vera-dark-grey-hover-dark, #292828)',
          'vera-dark-grey-opacity': 'var(--vera-dark-grey-opacity, #333333CD)',
          'vera-dark-grey-opacity-light': 'var(--vera-dark-grey-opacity-light, #333333CD)',
          'vera-dark-grey-opacity-dark': 'var(--vera-dark-grey-opacity-dark, #333333CD)',
          'vera-disabled': 'var(--vera-disabled, #E6E6E6)',
          'vera-disabled-light': 'var(--vera-disabled-light, #E6E6E6)',
          'vera-disabled-dark': 'var(--vera-disabled-dark, #333333)',
          'vera-error': 'var(--vera-error, #E61D1D)',
          'vera-error-light': 'var(--vera-error-light, #E61D1D)',
          'vera-error-dark': 'var(--vera-error-dark, #F75959)',
          'vera-error-hover': 'var(--vera-error-hover, #CD0000)',
          'vera-error-hover-light': 'var(--vera-error-hover-light, #CD0000)',
          'vera-error-hover-dark': 'var(--vera-error-hover-dark, #FE9696)',
          'vera-information': 'var(--vera-information, #0276D5)',
          'vera-information-light': 'var(--vera-information-light, #0276D5)',
          'vera-information-dark': 'var(--vera-information-dark, #2997F0)',
          'vera-information-background': 'var(--vera-information-background, #E8F4FB)',
          'vera-information-background-light': 'var(--vera-information-background-light, #E8F4FB)',
          'vera-information-background-dark': 'var(--vera-information-background-dark, #E8F4FB)',
          'vera-information-hover': 'var(--vera-information-hover, #2997F0)',
          'vera-information-hover-light': 'var(--vera-information-hover-light, #2997F0)',
          'vera-information-hover-dark': 'var(--vera-information-hover-dark, #0276D5)',
          'vera-on-accent': 'var(--vera-on-accent, #000000)',
          'vera-on-accent-light': 'var(--vera-on-accent-light, #000000)',
          'vera-on-accent-dark': 'var(--vera-on-accent-dark, #000000)',
          'vera-on-background': 'var(--vera-on-background, #757575)',
          'vera-on-background-light': 'var(--vera-on-background-light, #757575)',
          'vera-on-background-dark': 'var(--vera-on-background-dark, #B3B3B3)',
          'vera-on-dark-grey': 'var(--vera-on-dark-grey, #FFFFFF)',
          'vera-on-dark-grey-light': 'var(--vera-on-dark-grey-light, #FFFFFF)',
          'vera-on-dark-grey-dark': 'var(--vera-on-dark-grey-dark, #FFFFFF)',
          'vera-on-error': 'var(--vera-on-error, #FFFFFF)',
          'vera-on-error-light': 'var(--vera-on-error-light, #FFFFFF)',
          'vera-on-error-dark': 'var(--vera-on-error-dark, #000000)',
          'vera-on-information': 'var(--vera-on-information, #FFFFFF)',
          'vera-on-information-light': 'var(--vera-on-information-light, #FFFFFF)',
          'vera-on-information-dark': 'var(--vera-on-information-dark, #FFFFFF)',
          'vera-on-primary': 'var(--vera-on-primary, #FFFFFF)',
          'vera-on-primary-light': 'var(--vera-on-primary-light, #FFFFFF)',
          'vera-on-primary-dark': 'var(--vera-on-primary-dark, #000000)',
          'vera-on-secondary': 'var(--vera-on-secondary, #FFFFFF)',
          'vera-on-secondary-light': 'var(--vera-on-secondary-light, #FFFFFF)',
          'vera-on-secondary-dark': 'var(--vera-on-secondary-dark, #000000)',
          'vera-on-success': 'var(--vera-on-success, #FFFFFF)',
          'vera-on-success-light': 'var(--vera-on-success-light, #FFFFFF)',
          'vera-on-success-dark': 'var(--vera-on-success-dark, #000000)',
          'vera-on-surface': 'var(--vera-on-surface, #929292)',
          'vera-on-surface-light': 'var(--vera-on-surface-light, #929292)',
          'vera-on-surface-dark': 'var(--vera-on-surface-dark, #FFFFFF)',
          'vera-on-tertiary': 'var(--vera-on-tertiary, #FFFFFF)',
          'vera-on-tertiary-light': 'var(--vera-on-tertiary-light, #FFFFFF)',
          'vera-on-tertiary-dark': 'var(--vera-on-tertiary-dark, #000000)',
          'vera-on-warning': 'var(--vera-on-warning, #FFFFFF)',
          'vera-on-warning-light': 'var(--vera-on-warning-light, #FFFFFF)',
          'vera-on-warning-dark': 'var(--vera-on-warning-dark, #000000)',
          'vera-primary': 'var(--vera-primary, #9941FF)',
          'vera-primary-light': 'var(--vera-primary-light, #9941FF)',
          'vera-primary-dark': 'var(--vera-primary-dark, #B27BF2)',
          'vera-primary-hover': 'var(--vera-primary-hover, #871EFF)',
          'vera-primary-hover-light': 'var(--vera-primary-hover-light, #871EFF)',
          'vera-primary-hover-dark': 'var(--vera-primary-hover-dark, #CBA1FA)',
          'vera-secondary': 'var(--vera-secondary, #000000)',
          'vera-secondary-light': 'var(--vera-secondary-light, #000000)',
          'vera-secondary-dark': 'var(--vera-secondary-dark, #FFFFFF)',
          'vera-secondary-hover': 'var(--vera-secondary-hover, #666666)',
          'vera-secondary-hover-light': 'var(--vera-secondary-hover-light, #666666)',
          'vera-secondary-hover-dark': 'var(--vera-secondary-hover-dark, #929292)',
          'vera-skeleton-like': 'var(--vera-skeleton-like, #B3B3B3)',
          'vera-skeleton-like-light': 'var(--vera-skeleton-like-light, #B3B3B3)',
          'vera-skeleton-like-dark': 'var(--vera-skeleton-like-dark, #333333)',
          'vera-success': 'var(--vera-success, #1C8731)',
          'vera-success-light': 'var(--vera-success-light, #1C8731)',
          'vera-success-dark': 'var(--vera-success-dark, #30A849)',
          'vera-success-hover': 'var(--vera-success-hover, #1F7629)',
          'vera-success-hover-light': 'var(--vera-success-hover-light, #1F7629)',
          'vera-success-hover-dark': 'var(--vera-success-hover-dark, #53CA6A)',
          'vera-surface': 'var(--vera-surface, #FFFFFF)',
          'vera-surface-light': 'var(--vera-surface-light, #FFFFFF)',
          'vera-surface-dark': 'var(--vera-surface-dark, #000000)',
          'vera-tertiary': 'var(--vera-tertiary, #757575)',
          'vera-tertiary-light': 'var(--vera-tertiary-light, #757575)',
          'vera-tertiary-dark': 'var(--vera-tertiary-dark, #B3B3B3)',
          'vera-tertiary-hover': 'var(--vera-tertiary-hover, #929292)',
          'vera-tertiary-hover-light': 'var(--vera-tertiary-hover-light, #929292)',
          'vera-tertiary-hover-dark': 'var(--vera-tertiary-hover-dark, #B3B3B3)',
          'vera-text-disabled': 'var(--vera-text-disabled, #B3B3B3)',
          'vera-text-disabled-light': 'var(--vera-text-disabled-light, #B3B3B3)',
          'vera-text-disabled-dark': 'var(--vera-text-disabled-dark, #666666)',
          'vera-text-primary': 'var(--vera-text-primary, #9941FF)',
          'vera-text-primary-light': 'var(--vera-text-primary-light, #9941FF)',
          'vera-text-primary-dark': 'var(--vera-text-primary-dark, #B27BF2)',
          'vera-text-secondary': 'var(--vera-text-secondary, #000000)',
          'vera-text-secondary-light': 'var(--vera-text-secondary-light, #000000)',
          'vera-text-secondary-dark': 'var(--vera-text-secondary-dark, #FFFFFF)',
          'vera-text-tertiary': 'var(--vera-text-tertiary, #757575)',
          'vera-text-tertiary-light': 'var(--vera-text-tertiary-light, #757575)',
          'vera-text-tertiary-dark': 'var(--vera-text-tertiary-dark, #B3B3B3)',
          'vera-warning': 'var(--vera-warning, #BE5702)',
          'vera-warning-light': 'var(--vera-warning-light, #BE5702)',
          'vera-warning-dark': 'var(--vera-warning-dark, #FA9F00)',
          'vera-warning-hover': 'var(--vera-warning-hover, #A64C03)',
          'vera-warning-hover-light': 'var(--vera-warning-hover-light, #A64C03)',
          'vera-warning-hover-dark': 'var(--vera-warning-hover-dark, #FACC4B)',
        },
        fontFamily: {
          'vera-plain': [
            'Inter',
            'sans-serif',
            'system-ui',
            'ui-sans-serif',
            'Marker Felt',
            'Trebuchet MS',
          ],
        },
        screens: {
          'vera-mobile': {
            max: '767px',
          },
          'vera-desktop': {
            min: '768px',
          },
        },
      },
    },
  }
);

veraUI.safelist = ['vera-dark-mode'];

module.exports = veraUI;
