/**
 * Auto-generated Tailwind plugin for Vera design system
 * DO NOT EDIT MANUALLY - Generated by generateTailwindPlugin.ts
 */
// eslint-disable-next-line @typescript-eslint/no-require-imports
const plugin = require('tailwindcss/plugin');

/**
 * @typedef {Object} VeraTypographyProperties
 * @property {string} [fontSize]
 * @property {string} [lineHeight]
 * @property {string} [fontWeight]
 * @property {string} [mobileFontSize]
 * @property {string} [mobileLineHeight]
 * @property {string} [mobileFontWeight]
 */
/**
 * @typedef {Object} VeraColorThemeConfig
 * @property {string} [accent]
 * @property {string} [alertBackground]
 * @property {string} [alertBackgroundHover]
 * @property {string} [alertText]
 * @property {string} [background]
 * @property {string} [border]
 * @property {string} [darkBackground]
 * @property {string} [darkGrey]
 * @property {string} [darkGreyHover]
 * @property {string} [darkGreyOpacity]
 * @property {string} [disabled]
 * @property {string} [error]
 * @property {string} [errorHover]
 * @property {string} [information]
 * @property {string} [informationBackground]
 * @property {string} [informationHover]
 * @property {string} [onAccent]
 * @property {string} [onBackground]
 * @property {string} [onDarkGrey]
 * @property {string} [onError]
 * @property {string} [onInformation]
 * @property {string} [onPrimary]
 * @property {string} [onSecondary]
 * @property {string} [onSuccess]
 * @property {string} [onSurface]
 * @property {string} [onTertiary]
 * @property {string} [onWarning]
 * @property {string} [primary]
 * @property {string} [primaryHover]
 * @property {string} [secondary]
 * @property {string} [secondaryHover]
 * @property {string} [skeletonLike]
 * @property {string} [success]
 * @property {string} [successHover]
 * @property {string} [surface]
 * @property {string} [tertiary]
 * @property {string} [tertiaryHover]
 * @property {string} [textDisabled]
 * @property {string} [textPrimary]
 * @property {string} [textSecondary]
 * @property {string} [textTertiary]
 * @property {string} [warning]
 * @property {string} [warningHover]
 */
/**
 * @typedef {Object} VeraUIConfig
 * @property {VeraColorThemeConfig} [light]
 * @property {VeraColorThemeConfig} [dark]
 * @property {string} [borderRadiusExtraLarge]
 * @property {string} [borderRadiusExtraSmall]
 * @property {string} [borderRadiusLarge]
 * @property {string} [borderRadiusMedium]
 * @property {string} [borderRadiusNone]
 * @property {string} [borderRadiusSmall]
 * @property {string} [fontFamilyPlain]
 * @property {VeraTypographyProperties} [headline]
 * @property {VeraTypographyProperties} [subtitle]
 * @property {VeraTypographyProperties} [heading1]
 * @property {VeraTypographyProperties} [heading2]
 * @property {VeraTypographyProperties} [heading3]
 * @property {VeraTypographyProperties} [heading4]
 * @property {VeraTypographyProperties} [bodyExtended]
 * @property {VeraTypographyProperties} [bodyExtendedSemibold]
 * @property {VeraTypographyProperties} [bodyBase]
 * @property {VeraTypographyProperties} [bodyBaseSemibold]
 * @property {VeraTypographyProperties} [caption]
 * @property {VeraTypographyProperties} [captionSemibold]
 */

/**
 * @param {VeraUIConfig} [config={}]
 */

const veraUI = (config = {}) => {
  return plugin(
    ({ addUtilities, addBase, addVariant }) => {
      const { light = {}, dark = {} } = config; // also includes typography and layout
      const fontSizeUtilities = {};
      const fontWeightUtilities = {};

      // Add custom variants
      addVariant('child', '& > *');

      // Add CSS variables for theme-aware colors
      addBase({
        ':host, :root': {
          '--vera-accent': config.accent ?? light.accent ?? '#FFFFFF',
          '--vera-accent-light': config.accent ?? light.accent ?? '#FFFFFF',
          '--vera-accent-dark': config.accent ?? dark.accent ?? '#FFFFFF',
          '--vera-alert-background': config.alertBackground ?? light.alertBackground ?? '#FFEEF2',
          '--vera-alert-background-light':
            config.alertBackground ?? light.alertBackground ?? '#FFEEF2',
          '--vera-alert-background-dark':
            config.alertBackground ?? dark.alertBackground ?? '#3E0004',
          '--vera-alert-background-hover':
            config.alertBackgroundHover ?? light.alertBackgroundHover ?? '#FEDFDF',
          '--vera-alert-background-hover-light':
            config.alertBackgroundHover ?? light.alertBackgroundHover ?? '#FEDFDF',
          '--vera-alert-background-hover-dark':
            config.alertBackgroundHover ?? dark.alertBackgroundHover ?? '#6E0000',
          '--vera-alert-text': config.alertText ?? light.alertText ?? '#CD0000',
          '--vera-alert-text-light': config.alertText ?? light.alertText ?? '#CD0000',
          '--vera-alert-text-dark': config.alertText ?? dark.alertText ?? '#FEDFDF',
          '--vera-background': config.background ?? light.background ?? '#F5F0FD',
          '--vera-background-light': config.background ?? light.background ?? '#F5F0FD',
          '--vera-background-dark': config.background ?? dark.background ?? '#26044D',
          '--vera-border': config.border ?? light.border ?? '#E6E6E6',
          '--vera-border-light': config.border ?? light.border ?? '#E6E6E6',
          '--vera-border-dark': config.border ?? dark.border ?? '#333333',
          '--vera-dark-background': config.darkBackground ?? light.darkBackground ?? '#202124',
          '--vera-dark-background-light':
            config.darkBackground ?? light.darkBackground ?? '#202124',
          '--vera-dark-background-dark': config.darkBackground ?? dark.darkBackground ?? '#202124',
          '--vera-dark-grey': config.darkGrey ?? light.darkGrey ?? '#333333',
          '--vera-dark-grey-light': config.darkGrey ?? light.darkGrey ?? '#333333',
          '--vera-dark-grey-dark': config.darkGrey ?? dark.darkGrey ?? '#333333',
          '--vera-dark-grey-hover': config.darkGreyHover ?? light.darkGreyHover ?? '#292828',
          '--vera-dark-grey-hover-light': config.darkGreyHover ?? light.darkGreyHover ?? '#292828',
          '--vera-dark-grey-hover-dark': config.darkGreyHover ?? dark.darkGreyHover ?? '#292828',
          '--vera-dark-grey-opacity':
            config.darkGreyOpacity ?? light.darkGreyOpacity ?? '#333333CD',
          '--vera-dark-grey-opacity-light':
            config.darkGreyOpacity ?? light.darkGreyOpacity ?? '#333333CD',
          '--vera-dark-grey-opacity-dark':
            config.darkGreyOpacity ?? dark.darkGreyOpacity ?? '#333333CD',
          '--vera-disabled': config.disabled ?? light.disabled ?? '#E6E6E6',
          '--vera-disabled-light': config.disabled ?? light.disabled ?? '#E6E6E6',
          '--vera-disabled-dark': config.disabled ?? dark.disabled ?? '#333333',
          '--vera-error': config.error ?? light.error ?? '#E61D1D',
          '--vera-error-light': config.error ?? light.error ?? '#E61D1D',
          '--vera-error-dark': config.error ?? dark.error ?? '#F75959',
          '--vera-error-hover': config.errorHover ?? light.errorHover ?? '#CD0000',
          '--vera-error-hover-light': config.errorHover ?? light.errorHover ?? '#CD0000',
          '--vera-error-hover-dark': config.errorHover ?? dark.errorHover ?? '#FE9696',
          '--vera-information': config.information ?? light.information ?? '#0276D5',
          '--vera-information-light': config.information ?? light.information ?? '#0276D5',
          '--vera-information-dark': config.information ?? dark.information ?? '#2997F0',
          '--vera-information-background':
            config.informationBackground ?? light.informationBackground ?? '#E8F4FB',
          '--vera-information-background-light':
            config.informationBackground ?? light.informationBackground ?? '#E8F4FB',
          '--vera-information-background-dark':
            config.informationBackground ?? dark.informationBackground ?? '#E8F4FB',
          '--vera-information-hover':
            config.informationHover ?? light.informationHover ?? '#2997F0',
          '--vera-information-hover-light':
            config.informationHover ?? light.informationHover ?? '#2997F0',
          '--vera-information-hover-dark':
            config.informationHover ?? dark.informationHover ?? '#0276D5',
          '--vera-on-accent': config.onAccent ?? light.onAccent ?? '#000000',
          '--vera-on-accent-light': config.onAccent ?? light.onAccent ?? '#000000',
          '--vera-on-accent-dark': config.onAccent ?? dark.onAccent ?? '#000000',
          '--vera-on-background': config.onBackground ?? light.onBackground ?? '#757575',
          '--vera-on-background-light': config.onBackground ?? light.onBackground ?? '#757575',
          '--vera-on-background-dark': config.onBackground ?? dark.onBackground ?? '#B3B3B3',
          '--vera-on-dark-grey': config.onDarkGrey ?? light.onDarkGrey ?? '#FFFFFF',
          '--vera-on-dark-grey-light': config.onDarkGrey ?? light.onDarkGrey ?? '#FFFFFF',
          '--vera-on-dark-grey-dark': config.onDarkGrey ?? dark.onDarkGrey ?? '#FFFFFF',
          '--vera-on-error': config.onError ?? light.onError ?? '#FFFFFF',
          '--vera-on-error-light': config.onError ?? light.onError ?? '#FFFFFF',
          '--vera-on-error-dark': config.onError ?? dark.onError ?? '#000000',
          '--vera-on-information': config.onInformation ?? light.onInformation ?? '#FFFFFF',
          '--vera-on-information-light': config.onInformation ?? light.onInformation ?? '#FFFFFF',
          '--vera-on-information-dark': config.onInformation ?? dark.onInformation ?? '#FFFFFF',
          '--vera-on-primary': config.onPrimary ?? light.onPrimary ?? '#FFFFFF',
          '--vera-on-primary-light': config.onPrimary ?? light.onPrimary ?? '#FFFFFF',
          '--vera-on-primary-dark': config.onPrimary ?? dark.onPrimary ?? '#000000',
          '--vera-on-secondary': config.onSecondary ?? light.onSecondary ?? '#FFFFFF',
          '--vera-on-secondary-light': config.onSecondary ?? light.onSecondary ?? '#FFFFFF',
          '--vera-on-secondary-dark': config.onSecondary ?? dark.onSecondary ?? '#000000',
          '--vera-on-success': config.onSuccess ?? light.onSuccess ?? '#FFFFFF',
          '--vera-on-success-light': config.onSuccess ?? light.onSuccess ?? '#FFFFFF',
          '--vera-on-success-dark': config.onSuccess ?? dark.onSuccess ?? '#000000',
          '--vera-on-surface': config.onSurface ?? light.onSurface ?? '#929292',
          '--vera-on-surface-light': config.onSurface ?? light.onSurface ?? '#929292',
          '--vera-on-surface-dark': config.onSurface ?? dark.onSurface ?? '#FFFFFF',
          '--vera-on-tertiary': config.onTertiary ?? light.onTertiary ?? '#FFFFFF',
          '--vera-on-tertiary-light': config.onTertiary ?? light.onTertiary ?? '#FFFFFF',
          '--vera-on-tertiary-dark': config.onTertiary ?? dark.onTertiary ?? '#000000',
          '--vera-on-warning': config.onWarning ?? light.onWarning ?? '#FFFFFF',
          '--vera-on-warning-light': config.onWarning ?? light.onWarning ?? '#FFFFFF',
          '--vera-on-warning-dark': config.onWarning ?? dark.onWarning ?? '#000000',
          '--vera-primary': config.primary ?? light.primary ?? '#9941FF',
          '--vera-primary-light': config.primary ?? light.primary ?? '#9941FF',
          '--vera-primary-dark': config.primary ?? dark.primary ?? '#B27BF2',
          '--vera-primary-hover': config.primaryHover ?? light.primaryHover ?? '#871EFF',
          '--vera-primary-hover-light': config.primaryHover ?? light.primaryHover ?? '#871EFF',
          '--vera-primary-hover-dark': config.primaryHover ?? dark.primaryHover ?? '#CBA1FA',
          '--vera-secondary': config.secondary ?? light.secondary ?? '#000000',
          '--vera-secondary-light': config.secondary ?? light.secondary ?? '#000000',
          '--vera-secondary-dark': config.secondary ?? dark.secondary ?? '#FFFFFF',
          '--vera-secondary-hover': config.secondaryHover ?? light.secondaryHover ?? '#666666',
          '--vera-secondary-hover-light':
            config.secondaryHover ?? light.secondaryHover ?? '#666666',
          '--vera-secondary-hover-dark': config.secondaryHover ?? dark.secondaryHover ?? '#929292',
          '--vera-skeleton-like': config.skeletonLike ?? light.skeletonLike ?? '#B3B3B3',
          '--vera-skeleton-like-light': config.skeletonLike ?? light.skeletonLike ?? '#B3B3B3',
          '--vera-skeleton-like-dark': config.skeletonLike ?? dark.skeletonLike ?? '#333333',
          '--vera-success': config.success ?? light.success ?? '#1C8731',
          '--vera-success-light': config.success ?? light.success ?? '#1C8731',
          '--vera-success-dark': config.success ?? dark.success ?? '#30A849',
          '--vera-success-hover': config.successHover ?? light.successHover ?? '#1F7629',
          '--vera-success-hover-light': config.successHover ?? light.successHover ?? '#1F7629',
          '--vera-success-hover-dark': config.successHover ?? dark.successHover ?? '#53CA6A',
          '--vera-surface': config.surface ?? light.surface ?? '#FFFFFF',
          '--vera-surface-light': config.surface ?? light.surface ?? '#FFFFFF',
          '--vera-surface-dark': config.surface ?? dark.surface ?? '#000000',
          '--vera-tertiary': config.tertiary ?? light.tertiary ?? '#757575',
          '--vera-tertiary-light': config.tertiary ?? light.tertiary ?? '#757575',
          '--vera-tertiary-dark': config.tertiary ?? dark.tertiary ?? '#B3B3B3',
          '--vera-tertiary-hover': config.tertiaryHover ?? light.tertiaryHover ?? '#929292',
          '--vera-tertiary-hover-light': config.tertiaryHover ?? light.tertiaryHover ?? '#929292',
          '--vera-tertiary-hover-dark': config.tertiaryHover ?? dark.tertiaryHover ?? '#B3B3B3',
          '--vera-text-disabled': config.textDisabled ?? light.textDisabled ?? '#B3B3B3',
          '--vera-text-disabled-light': config.textDisabled ?? light.textDisabled ?? '#B3B3B3',
          '--vera-text-disabled-dark': config.textDisabled ?? dark.textDisabled ?? '#666666',
          '--vera-text-primary': config.textPrimary ?? light.textPrimary ?? '#9941FF',
          '--vera-text-primary-light': config.textPrimary ?? light.textPrimary ?? '#9941FF',
          '--vera-text-primary-dark': config.textPrimary ?? dark.textPrimary ?? '#B27BF2',
          '--vera-text-secondary': config.textSecondary ?? light.textSecondary ?? '#000000',
          '--vera-text-secondary-light': config.textSecondary ?? light.textSecondary ?? '#000000',
          '--vera-text-secondary-dark': config.textSecondary ?? dark.textSecondary ?? '#FFFFFF',
          '--vera-text-tertiary': config.textTertiary ?? light.textTertiary ?? '#757575',
          '--vera-text-tertiary-light': config.textTertiary ?? light.textTertiary ?? '#757575',
          '--vera-text-tertiary-dark': config.textTertiary ?? dark.textTertiary ?? '#B3B3B3',
          '--vera-warning': config.warning ?? light.warning ?? '#BE5702',
          '--vera-warning-light': config.warning ?? light.warning ?? '#BE5702',
          '--vera-warning-dark': config.warning ?? dark.warning ?? '#FA9F00',
          '--vera-warning-hover': config.warningHover ?? light.warningHover ?? '#A64C03',
          '--vera-warning-hover-light': config.warningHover ?? light.warningHover ?? '#A64C03',
          '--vera-warning-hover-dark': config.warningHover ?? dark.warningHover ?? '#FACC4B',

          // Typography and layout design tokens
          '--vera-border-radius-extra-large': config.borderRadiusExtraLarge ?? '24px',
          '--vera-border-radius-extra-small': config.borderRadiusExtraSmall ?? '2px',
          '--vera-border-radius-large': config.borderRadiusLarge ?? '12px',
          '--vera-border-radius-medium': config.borderRadiusMedium ?? '8px',
          '--vera-border-radius-none': config.borderRadiusNone ?? '0px',
          '--vera-border-radius-small': config.borderRadiusSmall ?? '4px',
          '--vera-font-family-plain':
            config.fontFamilyPlain ??
            'Inter, sans-serif, system-ui, ui-sans-serif, Marker Felt, Trebuchet MS',
          '--vera-typography-headline-font-size': config.headline?.fontSize ?? '4.125rem',
          '--vera-typography-headline-line-height': config.headline?.lineHeight ?? '5.5rem',
          '--vera-typography-headline-font-weight': config.headline?.fontWeight ?? '500',
          '--vera-typography-headline-mobile-font-size': config.headline?.mobileFontSize ?? '2rem',
          '--vera-typography-headline-mobile-line-height':
            config.headline?.mobileLineHeight ?? '2.5rem',
          '--vera-typography-headline-mobile-font-weight':
            config.headline?.mobileFontWeight ?? '500',
          '--vera-typography-subtitle-font-size': config.subtitle?.fontSize ?? '3.25rem',
          '--vera-typography-subtitle-line-height': config.subtitle?.lineHeight ?? '4.25rem',
          '--vera-typography-subtitle-font-weight': config.subtitle?.fontWeight ?? '500',
          '--vera-typography-subtitle-mobile-font-size':
            config.subtitle?.mobileFontSize ?? '1.875rem',
          '--vera-typography-subtitle-mobile-line-height':
            config.subtitle?.mobileLineHeight ?? '2.375rem',
          '--vera-typography-subtitle-mobile-font-weight':
            config.subtitle?.mobileFontWeight ?? '500',
          '--vera-typography-heading-1-font-size': config.heading1?.fontSize ?? '2.5rem',
          '--vera-typography-heading-1-line-height': config.heading1?.lineHeight ?? '3.25rem',
          '--vera-typography-heading-1-font-weight': config.heading1?.fontWeight ?? '500',
          '--vera-typography-heading-1-mobile-font-size':
            config.heading1?.mobileFontSize ?? '1.75rem',
          '--vera-typography-heading-1-mobile-line-height':
            config.heading1?.mobileLineHeight ?? '2.25rem',
          '--vera-typography-heading-1-mobile-font-weight':
            config.heading1?.mobileFontWeight ?? '500',
          '--vera-typography-heading-2-font-size': config.heading2?.fontSize ?? '2rem',
          '--vera-typography-heading-2-line-height': config.heading2?.lineHeight ?? '2.75rem',
          '--vera-typography-heading-2-font-weight': config.heading2?.fontWeight ?? '500',
          '--vera-typography-heading-2-mobile-font-size':
            config.heading2?.mobileFontSize ?? '1.5rem',
          '--vera-typography-heading-2-mobile-line-height':
            config.heading2?.mobileLineHeight ?? '2rem',
          '--vera-typography-heading-2-mobile-font-weight':
            config.heading2?.mobileFontWeight ?? '500',
          '--vera-typography-heading-3-font-size': config.heading3?.fontSize ?? '1.625rem',
          '--vera-typography-heading-3-line-height': config.heading3?.lineHeight ?? '2.25rem',
          '--vera-typography-heading-3-font-weight': config.heading3?.fontWeight ?? '500',
          '--vera-typography-heading-3-mobile-font-size':
            config.heading3?.mobileFontSize ?? '1.25rem',
          '--vera-typography-heading-3-mobile-line-height':
            config.heading3?.mobileLineHeight ?? '1.75rem',
          '--vera-typography-heading-3-mobile-font-weight':
            config.heading3?.mobileFontWeight ?? '500',
          '--vera-typography-heading-4-font-size': config.heading4?.fontSize ?? '1.25rem',
          '--vera-typography-heading-4-line-height': config.heading4?.lineHeight ?? '1.75rem',
          '--vera-typography-heading-4-font-weight': config.heading4?.fontWeight ?? '500',
          '--vera-typography-heading-4-mobile-font-size':
            config.heading4?.mobileFontSize ?? '1.125rem',
          '--vera-typography-heading-4-mobile-line-height':
            config.heading4?.mobileLineHeight ?? '1.5rem',
          '--vera-typography-heading-4-mobile-font-weight':
            config.heading4?.mobileFontWeight ?? '500',
          '--vera-typography-body-extended-font-size': config.bodyExtended?.fontSize ?? '1rem',
          '--vera-typography-body-extended-line-height':
            config.bodyExtended?.lineHeight ?? '1.5rem',
          '--vera-typography-body-extended-font-weight': config.bodyExtended?.fontWeight ?? '400',
          '--vera-typography-body-extended-mobile-font-size':
            config.bodyExtended?.mobileFontSize ?? '1rem',
          '--vera-typography-body-extended-mobile-line-height':
            config.bodyExtended?.mobileLineHeight ?? '1.5rem',
          '--vera-typography-body-extended-mobile-font-weight':
            config.bodyExtended?.mobileFontWeight ?? '400',
          '--vera-typography-body-extended-semibold-font-size':
            config.bodyExtendedSemibold?.fontSize ?? '1rem',
          '--vera-typography-body-extended-semibold-line-height':
            config.bodyExtendedSemibold?.lineHeight ?? '1.5rem',
          '--vera-typography-body-extended-semibold-font-weight':
            config.bodyExtendedSemibold?.fontWeight ?? '600',
          '--vera-typography-body-extended-semibold-mobile-font-size':
            config.bodyExtendedSemibold?.mobileFontSize ?? '1rem',
          '--vera-typography-body-extended-semibold-mobile-line-height':
            config.bodyExtendedSemibold?.mobileLineHeight ?? '1.5rem',
          '--vera-typography-body-extended-semibold-mobile-font-weight':
            config.bodyExtendedSemibold?.mobileFontWeight ?? '600',
          '--vera-typography-body-base-font-size': config.bodyBase?.fontSize ?? '0.875rem',
          '--vera-typography-body-base-line-height': config.bodyBase?.lineHeight ?? '1.25rem',
          '--vera-typography-body-base-font-weight': config.bodyBase?.fontWeight ?? '400',
          '--vera-typography-body-base-mobile-font-size':
            config.bodyBase?.mobileFontSize ?? '0.875rem',
          '--vera-typography-body-base-mobile-line-height':
            config.bodyBase?.mobileLineHeight ?? '1.25rem',
          '--vera-typography-body-base-mobile-font-weight':
            config.bodyBase?.mobileFontWeight ?? '400',
          '--vera-typography-body-base-semibold-font-size':
            config.bodyBaseSemibold?.fontSize ?? '0.875rem',
          '--vera-typography-body-base-semibold-line-height':
            config.bodyBaseSemibold?.lineHeight ?? '1.25rem',
          '--vera-typography-body-base-semibold-font-weight':
            config.bodyBaseSemibold?.fontWeight ?? '600',
          '--vera-typography-body-base-semibold-mobile-font-size':
            config.bodyBaseSemibold?.mobileFontSize ?? '0.875rem',
          '--vera-typography-body-base-semibold-mobile-line-height':
            config.bodyBaseSemibold?.mobileLineHeight ?? '1.25rem',
          '--vera-typography-body-base-semibold-mobile-font-weight':
            config.bodyBaseSemibold?.mobileFontWeight ?? '600',
          '--vera-typography-caption-font-size': config.caption?.fontSize ?? '0.75rem',
          '--vera-typography-caption-line-height': config.caption?.lineHeight ?? '1rem',
          '--vera-typography-caption-font-weight': config.caption?.fontWeight ?? '400',
          '--vera-typography-caption-mobile-font-size': config.caption?.mobileFontSize ?? '0.75rem',
          '--vera-typography-caption-mobile-line-height':
            config.caption?.mobileLineHeight ?? '1rem',
          '--vera-typography-caption-mobile-font-weight': config.caption?.mobileFontWeight ?? '400',
          '--vera-typography-caption-semibold-font-size':
            config.captionSemibold?.fontSize ?? '0.75rem',
          '--vera-typography-caption-semibold-line-height':
            config.captionSemibold?.lineHeight ?? '1rem',
          '--vera-typography-caption-semibold-font-weight':
            config.captionSemibold?.fontWeight ?? '600',
          '--vera-typography-caption-semibold-mobile-font-size':
            config.captionSemibold?.mobileFontSize ?? '0.75rem',
          '--vera-typography-caption-semibold-mobile-line-height':
            config.captionSemibold?.mobileLineHeight ?? '1rem',
          '--vera-typography-caption-semibold-mobile-font-weight':
            config.captionSemibold?.mobileFontWeight ?? '600',
        },
        ':host(.vera-dark-mode), :host(.dark), html.vera-dark-mode': {
          '--vera-accent': config.accent ?? dark.accent ?? '#FFFFFF',
          '--vera-alert-background': config.alertBackground ?? dark.alertBackground ?? '#3E0004',
          '--vera-alert-background-hover':
            config.alertBackgroundHover ?? dark.alertBackgroundHover ?? '#6E0000',
          '--vera-alert-text': config.alertText ?? dark.alertText ?? '#FEDFDF',
          '--vera-background': config.background ?? dark.background ?? '#26044D',
          '--vera-border': config.border ?? dark.border ?? '#333333',
          '--vera-dark-background': config.darkBackground ?? dark.darkBackground ?? '#202124',
          '--vera-dark-grey': config.darkGrey ?? dark.darkGrey ?? '#333333',
          '--vera-dark-grey-hover': config.darkGreyHover ?? dark.darkGreyHover ?? '#292828',
          '--vera-dark-grey-opacity': config.darkGreyOpacity ?? dark.darkGreyOpacity ?? '#333333CD',
          '--vera-disabled': config.disabled ?? dark.disabled ?? '#333333',
          '--vera-error': config.error ?? dark.error ?? '#F75959',
          '--vera-error-hover': config.errorHover ?? dark.errorHover ?? '#FE9696',
          '--vera-information': config.information ?? dark.information ?? '#2997F0',
          '--vera-information-background':
            config.informationBackground ?? dark.informationBackground ?? '#E8F4FB',
          '--vera-information-hover': config.informationHover ?? dark.informationHover ?? '#0276D5',
          '--vera-on-accent': config.onAccent ?? dark.onAccent ?? '#000000',
          '--vera-on-background': config.onBackground ?? dark.onBackground ?? '#B3B3B3',
          '--vera-on-dark-grey': config.onDarkGrey ?? dark.onDarkGrey ?? '#FFFFFF',
          '--vera-on-error': config.onError ?? dark.onError ?? '#000000',
          '--vera-on-information': config.onInformation ?? dark.onInformation ?? '#FFFFFF',
          '--vera-on-primary': config.onPrimary ?? dark.onPrimary ?? '#000000',
          '--vera-on-secondary': config.onSecondary ?? dark.onSecondary ?? '#000000',
          '--vera-on-success': config.onSuccess ?? dark.onSuccess ?? '#000000',
          '--vera-on-surface': config.onSurface ?? dark.onSurface ?? '#FFFFFF',
          '--vera-on-tertiary': config.onTertiary ?? dark.onTertiary ?? '#000000',
          '--vera-on-warning': config.onWarning ?? dark.onWarning ?? '#000000',
          '--vera-primary': config.primary ?? dark.primary ?? '#B27BF2',
          '--vera-primary-hover': config.primaryHover ?? dark.primaryHover ?? '#CBA1FA',
          '--vera-secondary': config.secondary ?? dark.secondary ?? '#FFFFFF',
          '--vera-secondary-hover': config.secondaryHover ?? dark.secondaryHover ?? '#929292',
          '--vera-skeleton-like': config.skeletonLike ?? dark.skeletonLike ?? '#333333',
          '--vera-success': config.success ?? dark.success ?? '#30A849',
          '--vera-success-hover': config.successHover ?? dark.successHover ?? '#53CA6A',
          '--vera-surface': config.surface ?? dark.surface ?? '#000000',
          '--vera-tertiary': config.tertiary ?? dark.tertiary ?? '#B3B3B3',
          '--vera-tertiary-hover': config.tertiaryHover ?? dark.tertiaryHover ?? '#B3B3B3',
          '--vera-text-disabled': config.textDisabled ?? dark.textDisabled ?? '#666666',
          '--vera-text-primary': config.textPrimary ?? dark.textPrimary ?? '#B27BF2',
          '--vera-text-secondary': config.textSecondary ?? dark.textSecondary ?? '#FFFFFF',
          '--vera-text-tertiary': config.textTertiary ?? dark.textTertiary ?? '#B3B3B3',
          '--vera-warning': config.warning ?? dark.warning ?? '#FA9F00',
          '--vera-warning-hover': config.warningHover ?? dark.warningHover ?? '#FACC4B',
        },
      });
      // headline
      fontSizeUtilities['.text-vera-headline'] = {
        fontSize: '2rem',
        lineHeight: '2.5rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-headline-font-size, 4.125rem)',
          lineHeight: 'var(--vera-typography-headline-line-height, 5.5rem)',
          fontWeight: 'var(--vera-typography-headline-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-headline'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-headline-font-weight, 500)',
        },
      };

      // subtitle
      fontSizeUtilities['.text-vera-subtitle'] = {
        fontSize: '1.875rem',
        lineHeight: '2.375rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-subtitle-font-size, 3.25rem)',
          lineHeight: 'var(--vera-typography-subtitle-line-height, 4.25rem)',
          fontWeight: 'var(--vera-typography-subtitle-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-subtitle'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-subtitle-font-weight, 500)',
        },
      };

      // heading-1
      fontSizeUtilities['.text-vera-heading-1'] = {
        fontSize: '1.75rem',
        lineHeight: '2.25rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-heading-1-font-size, 2.5rem)',
          lineHeight: 'var(--vera-typography-heading-1-line-height, 3.25rem)',
          fontWeight: 'var(--vera-typography-heading-1-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-heading-1'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-heading-1-font-weight, 500)',
        },
      };

      // heading-2
      fontSizeUtilities['.text-vera-heading-2'] = {
        fontSize: '1.5rem',
        lineHeight: '2rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-heading-2-font-size, 2rem)',
          lineHeight: 'var(--vera-typography-heading-2-line-height, 2.75rem)',
          fontWeight: 'var(--vera-typography-heading-2-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-heading-2'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-heading-2-font-weight, 500)',
        },
      };

      // heading-3
      fontSizeUtilities['.text-vera-heading-3'] = {
        fontSize: '1.25rem',
        lineHeight: '1.75rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-heading-3-font-size, 1.625rem)',
          lineHeight: 'var(--vera-typography-heading-3-line-height, 2.25rem)',
          fontWeight: 'var(--vera-typography-heading-3-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-heading-3'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-heading-3-font-weight, 500)',
        },
      };

      // heading-4
      fontSizeUtilities['.text-vera-heading-4'] = {
        fontSize: '1.125rem',
        lineHeight: '1.5rem',
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-heading-4-font-size, 1.25rem)',
          lineHeight: 'var(--vera-typography-heading-4-line-height, 1.75rem)',
          fontWeight: 'var(--vera-typography-heading-4-font-weight, 500)',
        },
      };

      fontWeightUtilities['.font-vera-heading-4'] = {
        fontWeight: 500,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-heading-4-font-weight, 500)',
        },
      };

      // body-extended
      fontSizeUtilities['.text-vera-body-extended'] = {
        fontSize: '1rem',
        lineHeight: '1.5rem',
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-body-extended-font-size, 1rem)',
          lineHeight: 'var(--vera-typography-body-extended-line-height, 1.5rem)',
          fontWeight: 'var(--vera-typography-body-extended-font-weight, 400)',
        },
      };

      fontWeightUtilities['.font-vera-body-extended'] = {
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-body-extended-font-weight, 400)',
        },
      };

      // body-extended-semibold
      fontSizeUtilities['.text-vera-body-extended-semibold'] = {
        fontSize: '1rem',
        lineHeight: '1.5rem',
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-body-extended-semibold-font-size, 1rem)',
          lineHeight: 'var(--vera-typography-body-extended-semibold-line-height, 1.5rem)',
          fontWeight: 'var(--vera-typography-body-extended-semibold-font-weight, 600)',
        },
      };

      fontWeightUtilities['.font-vera-body-extended-semibold'] = {
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-body-extended-semibold-font-weight, 600)',
        },
      };

      // body-base
      fontSizeUtilities['.text-vera-body-base'] = {
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-body-base-font-size, 0.875rem)',
          lineHeight: 'var(--vera-typography-body-base-line-height, 1.25rem)',
          fontWeight: 'var(--vera-typography-body-base-font-weight, 400)',
        },
      };

      fontWeightUtilities['.font-vera-body-base'] = {
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-body-base-font-weight, 400)',
        },
      };

      // body-base-semibold
      fontSizeUtilities['.text-vera-body-base-semibold'] = {
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-body-base-semibold-font-size, 0.875rem)',
          lineHeight: 'var(--vera-typography-body-base-semibold-line-height, 1.25rem)',
          fontWeight: 'var(--vera-typography-body-base-semibold-font-weight, 600)',
        },
      };

      fontWeightUtilities['.font-vera-body-base-semibold'] = {
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-body-base-semibold-font-weight, 600)',
        },
      };

      // caption
      fontSizeUtilities['.text-vera-caption'] = {
        fontSize: '0.75rem',
        lineHeight: '1rem',
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-caption-font-size, 0.75rem)',
          lineHeight: 'var(--vera-typography-caption-line-height, 1rem)',
          fontWeight: 'var(--vera-typography-caption-font-weight, 400)',
        },
      };

      fontWeightUtilities['.font-vera-caption'] = {
        fontWeight: 400,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-caption-font-weight, 400)',
        },
      };

      // caption-semibold
      fontSizeUtilities['.text-vera-caption-semibold'] = {
        fontSize: '0.75rem',
        lineHeight: '1rem',
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontSize: 'var(--vera-typography-caption-semibold-font-size, 0.75rem)',
          lineHeight: 'var(--vera-typography-caption-semibold-line-height, 1rem)',
          fontWeight: 'var(--vera-typography-caption-semibold-font-weight, 600)',
        },
      };

      fontWeightUtilities['.font-vera-caption-semibold'] = {
        fontWeight: 600,
        '@media (min-width: 768px)': {
          fontWeight: 'var(--vera-typography-caption-semibold-font-weight, 600)',
        },
      };

      addUtilities(fontSizeUtilities);
      addUtilities(fontWeightUtilities);
    },
    {
      theme: {
        extend: {
          borderRadius: {
            'vera-extra-large': 'var(--vera-border-radius-extra-large, 24px)',
            'vera-extra-small': 'var(--vera-border-radius-extra-small, 2px)',
            'vera-large': 'var(--vera-border-radius-large, 12px)',
            'vera-medium': 'var(--vera-border-radius-medium, 8px)',
            'vera-none': 'var(--vera-border-radius-none, 0px)',
            'vera-small': 'var(--vera-border-radius-small, 4px)',
          },
          colors: {
            'vera-accent': 'var(--vera-accent, #FFFFFF)',
            'vera-accent-light': 'var(--vera-accent-light, #FFFFFF)',
            'vera-accent-dark': 'var(--vera-accent-dark, #FFFFFF)',
            'vera-alert-background': 'var(--vera-alert-background, #FFEEF2)',
            'vera-alert-background-light': 'var(--vera-alert-background-light, #FFEEF2)',
            'vera-alert-background-dark': 'var(--vera-alert-background-dark, #3E0004)',
            'vera-alert-background-hover': 'var(--vera-alert-background-hover, #FEDFDF)',
            'vera-alert-background-hover-light':
              'var(--vera-alert-background-hover-light, #FEDFDF)',
            'vera-alert-background-hover-dark': 'var(--vera-alert-background-hover-dark, #6E0000)',
            'vera-alert-text': 'var(--vera-alert-text, #CD0000)',
            'vera-alert-text-light': 'var(--vera-alert-text-light, #CD0000)',
            'vera-alert-text-dark': 'var(--vera-alert-text-dark, #FEDFDF)',
            'vera-background': 'var(--vera-background, #F5F0FD)',
            'vera-background-light': 'var(--vera-background-light, #F5F0FD)',
            'vera-background-dark': 'var(--vera-background-dark, #26044D)',
            'vera-border': 'var(--vera-border, #E6E6E6)',
            'vera-border-light': 'var(--vera-border-light, #E6E6E6)',
            'vera-border-dark': 'var(--vera-border-dark, #333333)',
            'vera-dark-background': 'var(--vera-dark-background, #202124)',
            'vera-dark-background-light': 'var(--vera-dark-background-light, #202124)',
            'vera-dark-background-dark': 'var(--vera-dark-background-dark, #202124)',
            'vera-dark-grey': 'var(--vera-dark-grey, #333333)',
            'vera-dark-grey-light': 'var(--vera-dark-grey-light, #333333)',
            'vera-dark-grey-dark': 'var(--vera-dark-grey-dark, #333333)',
            'vera-dark-grey-hover': 'var(--vera-dark-grey-hover, #292828)',
            'vera-dark-grey-hover-light': 'var(--vera-dark-grey-hover-light, #292828)',
            'vera-dark-grey-hover-dark': 'var(--vera-dark-grey-hover-dark, #292828)',
            'vera-dark-grey-opacity': 'var(--vera-dark-grey-opacity, #333333CD)',
            'vera-dark-grey-opacity-light': 'var(--vera-dark-grey-opacity-light, #333333CD)',
            'vera-dark-grey-opacity-dark': 'var(--vera-dark-grey-opacity-dark, #333333CD)',
            'vera-disabled': 'var(--vera-disabled, #E6E6E6)',
            'vera-disabled-light': 'var(--vera-disabled-light, #E6E6E6)',
            'vera-disabled-dark': 'var(--vera-disabled-dark, #333333)',
            'vera-error': 'var(--vera-error, #E61D1D)',
            'vera-error-light': 'var(--vera-error-light, #E61D1D)',
            'vera-error-dark': 'var(--vera-error-dark, #F75959)',
            'vera-error-hover': 'var(--vera-error-hover, #CD0000)',
            'vera-error-hover-light': 'var(--vera-error-hover-light, #CD0000)',
            'vera-error-hover-dark': 'var(--vera-error-hover-dark, #FE9696)',
            'vera-information': 'var(--vera-information, #0276D5)',
            'vera-information-light': 'var(--vera-information-light, #0276D5)',
            'vera-information-dark': 'var(--vera-information-dark, #2997F0)',
            'vera-information-background': 'var(--vera-information-background, #E8F4FB)',
            'vera-information-background-light':
              'var(--vera-information-background-light, #E8F4FB)',
            'vera-information-background-dark': 'var(--vera-information-background-dark, #E8F4FB)',
            'vera-information-hover': 'var(--vera-information-hover, #2997F0)',
            'vera-information-hover-light': 'var(--vera-information-hover-light, #2997F0)',
            'vera-information-hover-dark': 'var(--vera-information-hover-dark, #0276D5)',
            'vera-on-accent': 'var(--vera-on-accent, #000000)',
            'vera-on-accent-light': 'var(--vera-on-accent-light, #000000)',
            'vera-on-accent-dark': 'var(--vera-on-accent-dark, #000000)',
            'vera-on-background': 'var(--vera-on-background, #757575)',
            'vera-on-background-light': 'var(--vera-on-background-light, #757575)',
            'vera-on-background-dark': 'var(--vera-on-background-dark, #B3B3B3)',
            'vera-on-dark-grey': 'var(--vera-on-dark-grey, #FFFFFF)',
            'vera-on-dark-grey-light': 'var(--vera-on-dark-grey-light, #FFFFFF)',
            'vera-on-dark-grey-dark': 'var(--vera-on-dark-grey-dark, #FFFFFF)',
            'vera-on-error': 'var(--vera-on-error, #FFFFFF)',
            'vera-on-error-light': 'var(--vera-on-error-light, #FFFFFF)',
            'vera-on-error-dark': 'var(--vera-on-error-dark, #000000)',
            'vera-on-information': 'var(--vera-on-information, #FFFFFF)',
            'vera-on-information-light': 'var(--vera-on-information-light, #FFFFFF)',
            'vera-on-information-dark': 'var(--vera-on-information-dark, #FFFFFF)',
            'vera-on-primary': 'var(--vera-on-primary, #FFFFFF)',
            'vera-on-primary-light': 'var(--vera-on-primary-light, #FFFFFF)',
            'vera-on-primary-dark': 'var(--vera-on-primary-dark, #000000)',
            'vera-on-secondary': 'var(--vera-on-secondary, #FFFFFF)',
            'vera-on-secondary-light': 'var(--vera-on-secondary-light, #FFFFFF)',
            'vera-on-secondary-dark': 'var(--vera-on-secondary-dark, #000000)',
            'vera-on-success': 'var(--vera-on-success, #FFFFFF)',
            'vera-on-success-light': 'var(--vera-on-success-light, #FFFFFF)',
            'vera-on-success-dark': 'var(--vera-on-success-dark, #000000)',
            'vera-on-surface': 'var(--vera-on-surface, #929292)',
            'vera-on-surface-light': 'var(--vera-on-surface-light, #929292)',
            'vera-on-surface-dark': 'var(--vera-on-surface-dark, #FFFFFF)',
            'vera-on-tertiary': 'var(--vera-on-tertiary, #FFFFFF)',
            'vera-on-tertiary-light': 'var(--vera-on-tertiary-light, #FFFFFF)',
            'vera-on-tertiary-dark': 'var(--vera-on-tertiary-dark, #000000)',
            'vera-on-warning': 'var(--vera-on-warning, #FFFFFF)',
            'vera-on-warning-light': 'var(--vera-on-warning-light, #FFFFFF)',
            'vera-on-warning-dark': 'var(--vera-on-warning-dark, #000000)',
            'vera-primary': 'var(--vera-primary, #9941FF)',
            'vera-primary-light': 'var(--vera-primary-light, #9941FF)',
            'vera-primary-dark': 'var(--vera-primary-dark, #B27BF2)',
            'vera-primary-hover': 'var(--vera-primary-hover, #871EFF)',
            'vera-primary-hover-light': 'var(--vera-primary-hover-light, #871EFF)',
            'vera-primary-hover-dark': 'var(--vera-primary-hover-dark, #CBA1FA)',
            'vera-secondary': 'var(--vera-secondary, #000000)',
            'vera-secondary-light': 'var(--vera-secondary-light, #000000)',
            'vera-secondary-dark': 'var(--vera-secondary-dark, #FFFFFF)',
            'vera-secondary-hover': 'var(--vera-secondary-hover, #666666)',
            'vera-secondary-hover-light': 'var(--vera-secondary-hover-light, #666666)',
            'vera-secondary-hover-dark': 'var(--vera-secondary-hover-dark, #929292)',
            'vera-skeleton-like': 'var(--vera-skeleton-like, #B3B3B3)',
            'vera-skeleton-like-light': 'var(--vera-skeleton-like-light, #B3B3B3)',
            'vera-skeleton-like-dark': 'var(--vera-skeleton-like-dark, #333333)',
            'vera-success': 'var(--vera-success, #1C8731)',
            'vera-success-light': 'var(--vera-success-light, #1C8731)',
            'vera-success-dark': 'var(--vera-success-dark, #30A849)',
            'vera-success-hover': 'var(--vera-success-hover, #1F7629)',
            'vera-success-hover-light': 'var(--vera-success-hover-light, #1F7629)',
            'vera-success-hover-dark': 'var(--vera-success-hover-dark, #53CA6A)',
            'vera-surface': 'var(--vera-surface, #FFFFFF)',
            'vera-surface-light': 'var(--vera-surface-light, #FFFFFF)',
            'vera-surface-dark': 'var(--vera-surface-dark, #000000)',
            'vera-tertiary': 'var(--vera-tertiary, #757575)',
            'vera-tertiary-light': 'var(--vera-tertiary-light, #757575)',
            'vera-tertiary-dark': 'var(--vera-tertiary-dark, #B3B3B3)',
            'vera-tertiary-hover': 'var(--vera-tertiary-hover, #929292)',
            'vera-tertiary-hover-light': 'var(--vera-tertiary-hover-light, #929292)',
            'vera-tertiary-hover-dark': 'var(--vera-tertiary-hover-dark, #B3B3B3)',
            'vera-text-disabled': 'var(--vera-text-disabled, #B3B3B3)',
            'vera-text-disabled-light': 'var(--vera-text-disabled-light, #B3B3B3)',
            'vera-text-disabled-dark': 'var(--vera-text-disabled-dark, #666666)',
            'vera-text-primary': 'var(--vera-text-primary, #9941FF)',
            'vera-text-primary-light': 'var(--vera-text-primary-light, #9941FF)',
            'vera-text-primary-dark': 'var(--vera-text-primary-dark, #B27BF2)',
            'vera-text-secondary': 'var(--vera-text-secondary, #000000)',
            'vera-text-secondary-light': 'var(--vera-text-secondary-light, #000000)',
            'vera-text-secondary-dark': 'var(--vera-text-secondary-dark, #FFFFFF)',
            'vera-text-tertiary': 'var(--vera-text-tertiary, #757575)',
            'vera-text-tertiary-light': 'var(--vera-text-tertiary-light, #757575)',
            'vera-text-tertiary-dark': 'var(--vera-text-tertiary-dark, #B3B3B3)',
            'vera-warning': 'var(--vera-warning, #BE5702)',
            'vera-warning-light': 'var(--vera-warning-light, #BE5702)',
            'vera-warning-dark': 'var(--vera-warning-dark, #FA9F00)',
            'vera-warning-hover': 'var(--vera-warning-hover, #A64C03)',
            'vera-warning-hover-light': 'var(--vera-warning-hover-light, #A64C03)',
            'vera-warning-hover-dark': 'var(--vera-warning-hover-dark, #FACC4B)',
          },
          fontFamily: {
            'vera-plain': [
              'var(--vera-font-family-plain, Inter, sans-serif, system-ui, ui-sans-serif, Marker Felt, Trebuchet MS)',
            ],
          },
          screens: {
            'vera-mobile': {
              max: '767px',
            },
            'vera-desktop': {
              min: '768px',
            },
          },
        },
      },
    }
  );
};

veraUI.safelist = ['vera-dark-mode'];

module.exports = veraUI;
