const customWordList = [
  'Opentok',
  'Vonage',
  'screensharing',
  'reconnections',
  'videocam',
  'issuetype',
  'Autolinker',
  'NOSONAR',
  'jiraiOSComponentId',
  'supportedLngs',
  'applinks',
  'precall',
  'Precall',
  'Rendererable',
  'Hydrateable',
  'firefoxUserPrefs',
  'gollum',
  'PWDEBUG',
  'unstub',
  'vonageAPIURL',
  'kbps',
  'Mbps',
  'customfield',
  'VIDSOL',
  'Frameguard',
  'hsts',
  'clickjacking',
  'COEP',
];

export default customWordList;
