sonar.projectKey=Vonage_vonage-video-react-app
sonar.organization=vonage

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=vonage-video-react-app
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
# sonar.sources=src

sonar.exclusions=\
node_modules/**

sonar.coverage.exclusions=\
tests/**,\
integration-tests/**,\
**/*.{spec,test}.ts{,x},\
scripts/**,\
customWordList.mjs,\
**/eslint.config.*,\
**/tailwind.config.*,\
**/test*/setup*.*,\
**/vite.config.*,\
**/webpack.config.*,\
libs/ui/src/theme/helpers/designTokens/**

# Disable duplications detection
sonar.cpd.exclusions=\
libs/ui/src/theme/helpers/designTokens/**

sonar.javascript.lcov.reportPaths=**/coverage/lcov.info
