sonar.host.url=https://sonarcloud.io
sonar.organization=rofim
sonar.projectKey=rofim_visio
sonar.projectName=rofim_visio
sonar.sourceEncoding=UTF-8
# sonar.sources=src

sonar.exclusions=\
node_modules/**

sonar.coverage.exclusions=\
tests/**,\
integration-tests/**,\
**/*.spec.ts,\
**/*.spec.tsx,\
**/*.test.ts,\
**/*.test.tsx,\
**/test/**,\
**/tests/**,\
scripts/**,\
customWordList.mjs,\
**/eslint.config.*,\
**/tailwind.config.*,\
**/test*/setup*.*,\
**/vite.config.*,\
**/webpack.config.*,\
libs/ui/src/theme/helpers/designTokens/**,\
frontend/src/test/mocks/vonageVideo.ts,

# Ignore "nested functions too deep" rule in test files
sonar.issue.ignore.multicriteria=nestingInTests
sonar.issue.ignore.multicriteria.nestingInTests.ruleKey=typescript:S2004
sonar.issue.ignore.multicriteria.nestingInTests.resourceKey=\
**/*.test.ts,\
**/*.test.tsx,\
**/*.spec.ts,\
**/*.spec.tsx,\
**/__tests__/**,\
**/tests/**,\
**/test/**


# Ignore "nested functions too deep" rule in test files
sonar.issue.ignore.multicriteria=nestingInTests
sonar.issue.ignore.multicriteria.nestingInTests.ruleKey=typescript:S2004
sonar.issue.ignore.multicriteria.nestingInTests.resourceKey=\
**/*.test.ts,\
**/*.test.tsx,\
**/*.spec.ts,\
**/*.spec.tsx,\
**/__tests__/**,\
**/tests/**,\
**/test/**


# Disable duplications detection
sonar.cpd.exclusions=\
tests/**,\
**/*.spec.ts,\
**/*.spec.tsx,\
**/*.test.ts,\
**/*.test.tsx,\
**/test/**,\
**/tests/**,\
**/test*/setup*.*,\
libs/ui/src/theme/helpers/designTokens/**,\
**/vite.config.*

sonar.javascript.lcov.reportPaths=**/coverage/lcov.info
