sonar.projectKey=Vonage_vonage-video-react-app
sonar.organization=vonage

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=vonage-video-react-app
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
# sonar.sources=src

sonar.exclusions=\
node_modules/**

sonar.coverage.exclusions=\
tests/**,\
integration-tests/**,\
**/*.spec.ts,\
**/*.spec.tsx,\
**/*.test.ts,\
**/*.test.tsx,\
**/test/**,\
**/tests/**,\
scripts/**,\
customWordList.mjs,\
**/eslint.config.*,\
**/tailwind.config.*,\
**/test*/setup*.*,\
**/vite.config.*,\
**/vite.*.config.*,\
**/webpack.config.*,\
libs/ui/src/theme/helpers/designTokens/**,\
libs/ui/src/theme/helpers/tailwind/**,\
frontend/src/test/mocks/vonageVideo.ts,\
# Exclude all Storybook files
**/.storybook/**,\
**/*.stories.tsx,\
**/*.stories.ts,\
**/*.story.tsx,\
**/*.story.ts,\
libs/common/test/**/*,\
libs/common/testBrowser/**,\
**/index.ts,\
**/index.tsx, \
**/example/**

# Ignore "nested functions too deep" rule in test files
sonar.issue.ignore.multicriteria=nestingInTests
sonar.issue.ignore.multicriteria.nestingInTests.ruleKey=typescript:S2004
sonar.issue.ignore.multicriteria.nestingInTests.resourceKey=\
**/*.test.ts,\
**/*.test.tsx,\
**/*.spec.ts,\
**/*.spec.tsx,\
**/__tests__/**,\
**/tests/**,\
**/test/**


# Ignore "nested functions too deep" rule in test files
sonar.issue.ignore.multicriteria=nestingInTests
sonar.issue.ignore.multicriteria.nestingInTests.ruleKey=typescript:S2004
sonar.issue.ignore.multicriteria.nestingInTests.resourceKey=\
**/*.test.ts,\
**/*.test.tsx,\
**/*.spec.ts,\
**/*.spec.tsx,\
**/__tests__/**,\
**/tests/**,\
**/test/**


# Disable duplications detection
sonar.cpd.exclusions=\
tests/**,\
**/*.spec.ts,\
**/*.spec.tsx,\
**/*.test.ts,\
**/*.test.tsx,\
**/test/**,\
**/tests/**,\
**/test*/setup*.*,\
libs/ui/src/theme/helpers/designTokens/**,\
**/vite.config.*,\
libs/ui/src/theme/helpers/tailwind/veraUI.cjs,\
scripts/**,\
libs/common/testBrowser/**

sonar.javascript.lcov.reportPaths=**/coverage/lcov.info,coverage-*/lcov.info
