#!/bin/bash

export ENABLE_REPORT_ISSUE=false
export I18N_FALLBACK_LANGUAGE='fr'
export I18N_SUPPORTED_LANGUAGES='de|en|es|fr|it|pt'
export ALLOW_BACKGROUND_EFFECTS=true
export ALLOW_CAMERA_CONTROL=true
export ALLOW_VIDEO_ON_JOIN=true
export DEFAULT_RESOLUTION='1280x720'
export ALLOW_ADVANCED_NOISE_SUPPRESSION=true
export ALLOW_AUDIO_ON_JOIN=true
export ALLOW_MICROPHONE_CONTROL=true
export MEETING_ROOM_ALLOW_DEVICE_SELECTION=true
export WAITING_ROOM_ALLOW_DEVICE_SELECTION=true
export ALLOW_ARCHIVING=false
export ALLOW_CAPTIONS=false
export ALLOW_CHAT=true
export DEVICE_SELECTION=true
export ALLOW_EMOJIS=false
export ALLOW_SCREEN_SHARE=true
export DEFAULT_LAYOUT_MODE='active-speaker'
export SHOW_PARTICIPANT_LIST=true
export BYPASS_WAITING_ROOM=true
