#!/bin/bash

export ENABLE_REPORT_ISSUE=true
export I18N_FALLBACK_LANGUAGE='en'
export I18N_SUPPORTED_LANGUAGES='en|en-US|es|es-MX|it|de'
export ALLOW_BACKGROUND_EFFECTS=true
export ALLOW_CAMERA_CONTROL=true
export ALLOW_VIDEO_ON_JOIN=true
export DEFAULT_RESOLUTION='1280x720'
export ALLOW_ADVANCED_NOISE_SUPPRESSION=true
export ALLOW_AUDIO_ON_JOIN=true
export ALLOW_MICROPHONE_CONTROL=true
export MEETING_ROOM_ALLOW_DEVICE_SELECTION=true
export WAITING_ROOM_ALLOW_DEVICE_SELECTION=true
export ALLOW_ARCHIVING=true
export ALLOW_CAPTIONS=true
export ALLOW_CHAT=true
export DEVICE_SELECTION=true
export ALLOW_EMOJIS=true
export ALLOW_SCREEN_SHARE=true
export DEFAULT_LAYOUT_MODE='active-speaker'
export SHOW_PARTICIPANT_LIST=true
