---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: video-react-ref-app # SERVICE NAME field
  title: Video React Ref App # Title (human-friendly library name) field
  description: Vonage Video API JS React reference application
  annotations:
    vonage.com/jira-id: VPF # video general projects
spec:
  type: library
  owner: group:orgdata/vdk # helm "owner" orgdata squad id or general orgdata/vid
  domain: video-api # Product this library belongs to
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: video-react-ref-app
  description: Video React Ref App Component
  annotations:
    github.com/project-slug: Vonage/vonage-video-react-app # GH repo
spec:
  type: library
  owner: group:orgdata/vdk
  system: video-react-ref-app
  lifecycle: production
  dependsOn:
    - component:default/video-js-sdk
