name: run-tests

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  VIDEO_SERVICE_PROVIDER: ${{vars.VIDEO_SERVICE_PROVIDER}}
  OT_API_KEY: ${{secrets.API_KEY}}
  OT_API_SECRET: ${{secrets.API_SECRET}}
  VONAGE_APP_ID: ${{secrets.VONAGE_APP_ID}}
  VONAGE_PRIVATE_KEY: ${{secrets.VONAGE_PRIVATE_KEY}}

jobs:
  run:
    runs-on: ubuntu-22.04

    steps:
      # ----------------------------------------------------
      # Skip CI if label is present
      # ----------------------------------------------------
      - name: Check for "skip-ci" label
        id: check-skip-ci
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(label => label.name);
            return labels.includes("skip-ci");

      - name: Skip CI
        if: steps.check-skip-ci.outputs.result == 'true'
        run: echo "Skipping CI :^)"

      # ----------------------------------------------------
      # Checkout
      # ----------------------------------------------------
      - name: Checkout
        if: steps.check-skip-ci.outputs.result == 'false'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ----------------------------------------------------
      # Install Chrome
      # ----------------------------------------------------
      - name: Install chrome latest
        if: steps.check-skip-ci.outputs.result == 'false'
        run: |
          wget --max-redirect=0 -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt update && sudo apt install -y google-chrome-stable 
          echo "Installed Chrome:"
          /usr/bin/google-chrome-stable --version

      # ----------------------------------------------------
      # Install Edge
      # ----------------------------------------------------
      - name: Install edge latest
        if: steps.check-skip-ci.outputs.result == 'false'
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-stable.list'
          sudo rm microsoft.gpg
          sudo apt update && sudo apt install -y microsoft-edge-stable
          echo "Installed Edge:"
          /usr/bin/microsoft-edge-stable --version

      # ----------------------------------------------------
      # Setup Node
      # ----------------------------------------------------
      - name: Setup node
        if: steps.check-skip-ci.outputs.result == 'false'
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn

      # ----------------------------------------------------
      # Install repository dependencies
      # ----------------------------------------------------
      - name: Install Dependencies
        if: steps.check-skip-ci.outputs.result == 'false'
        run: |
          node -v
          yarn --ignore-scripts

      # ----------------------------------------------------
      # Install Playwright browsers (Chromium, WebKit, Firefox)
      # ----------------------------------------------------
      - name: Install Playwright Browsers
        if: steps.check-skip-ci.outputs.result == 'false'
        run: npx playwright install --with-deps

      # ----------------------------------------------------
      # Run Unit Tests
      # ----------------------------------------------------
      - name: Run unit tests
        if: steps.check-skip-ci.outputs.result == 'false'
        run: |
          NX_DAEMON=false yarn test

      # ----------------------------------------------------
      # SonarCloud Scan PR
      # ----------------------------------------------------
      - name: SonarCloud Scan On PR
        if: steps.check-skip-ci.outputs.result == 'false' && github.event.pull_request.head.repo.fork == false
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_BRANCH: ${{ github.head_ref }}
          BASE_BRANCH: ${{ github.event.pull_request.head.ref }}
        with:
          args: >
            -Dsonar.pullrequest.key="$PR_NUMBER"
            -Dsonar.pullrequest.branch="$PR_BRANCH"
            -Dsonar.pullrequest.base="$BASE_BRANCH"

      # ----------------------------------------------------
      # SonarCloud Branch Analysis
      # ----------------------------------------------------
      - name: SonarCloud Branch Analysis On base branch
        if: steps.check-skip-ci.outputs.result == 'false' && github.event.pull_request.head.repo.fork == false
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          BASE_BRANCH: ${{ github.event.pull_request.head.ref }}
        with:
          args: >
            -Dsonar.branch.name="$BASE_BRANCH"

      # ----------------------------------------------------
      # Run Integration Tests (Playwright)
      # ----------------------------------------------------
      - name: Run integration tests
        if: steps.check-skip-ci.outputs.result == 'false' && github.event.pull_request.head.repo.fork == false
        run: |
          echo "VIDEO_SERVICE_PROVIDER: $VIDEO_SERVICE_PROVIDER"
          Xvfb :99 & export DISPLAY=:99
          yarn test:integration
