name: SonarCloud Analysis for tags

on:
  push:
    tags:
      - '*.*.*'

jobs:
  frontend-analysis:
    name: Frontend Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run frontend tests
        run: yarn test:frontend coverage

      - name: SonarCloud Scan
        if: ${{ !cancelled() }}
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          SONAR_TOKEN: ${{ secrets.FRONTEND_SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ github.ref_name }}
            -Dsonar.branch.name=master
