name: Start AWS pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        required: true
        options:
          - staging
          - preprod
          - prod

jobs:
  deploy:
    name: Deploy visio to ${{ github.ref_name == 'develop' && 'staging' || inputs.environment }}
    uses: ./.github/workflows/common-aws-pipeline-steps.yaml
    with:
      apps: visio
      environment: ${{ github.ref_name == 'develop' && 'staging' || inputs.environment }}

  deployment-gate:
    name: Deployment completed
    needs: [deploy]
    if: success()
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ github.ref_name == 'develop' && 'staging' || inputs.environment }}
    steps:
      - name: Summary
        run: echo "Pipeline visio deployed to ${{ github.ref_name == 'develop' && 'staging' || inputs.environment }}"
